# Generated by Django 2.1.7 on 2019-03-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='country',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='paypal_email',
        ),
    ]
