version: '3'
services:
  web-backend:
    build: 
      context: .
      dockerfile: Dockerfile-backend
    image: carrot123/django-project:1.0
    ports:
      - "8000:8000"
    restart: always
    volumes:
      # - ./project-backend:/go/src/github.com/lart2000/project-backend
      - ./dope_places_backend:/usr/src/app/dope_places_backend
    # command: [ "sh", "-c", "cd /go/src/github.com/lart2000/coreabeautyperu/project-backend buffalo dev" ] 
    command: [ "sh", "-c", "cd /usr/src/app/dope_places_backend && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" ] 
    # command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    tty: 'true'

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=dope_places
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      backend:
        ipv4_address: 172.20.0.6
networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

