# Generated by Django 2.1.5 on 2019-01-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20190125_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
