# Generated by Django 2.1.7 on 2019-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20190202_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes_proxy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_proxy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
