# Generated by Django 2.1.7 on 2019-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20190202_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
