# Generated by Django 2.1.7 on 2019-02-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20190226_1127'),
        ('items', '0009_auto_20190219_1246'),
    ]

    operations = [
    ]
