# Generated by Django 2.1.7 on 2019-03-12 19:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=64)),
                ('payer_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
            ],
        ),
    ]
