# Generated by Django 2.1.5 on 2019-01-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('customers', '0001_initial'),
        ('proxies', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('items', models.ManyToManyField(to='items.Item')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxies.Proxy')),
            ],
        ),
    ]
