# Generated by Django 2.1.5 on 2019-01-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('00', 'Draft'), ('01', 'Posted'), ('02', 'Matched'), ('03', 'Confirm & Pay'), ('04', 'Shopping'), ('05', 'Pay Shipping'), ('06', 'Delivery')], default='00', max_length=2),
        ),
    ]
