# Generated by Django 2.1.7 on 2019-02-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190125_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('00', 'Draft'), ('01', 'Posted'), ('02', 'Matched'), ('03', 'Confirm & Pay'), ('04', 'Shopping'), ('05', 'Pay Shipping'), ('06', 'Delivery'), ('07', 'Delivered')], default='00', max_length=2),
        ),
    ]
